from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.signout, name='logout'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('changePasswordPost/', views.changePasswordPost,
         name='changePasswordPost'),
    path('signuppost/', views.signuppost, name='signuppost'),
    path('signinpost/', views.signinpost, name='signinpost'),
    path('addpatientcard/', views.addpatientcard, name='addpatientcard'),
    path('searchpatient/', views.searchpatient, name='searchpatient'),
    path('getpatientdata/', views.getpatientdata, name='getpatientdata'),
    path('getpatientdataforassistant/', views.getpatientdataforassistant,
         name='getpatientdataforassistant'),
    path('setdoctordata/', views.setdoctordata, name='setdoctordata'),
    path('update_is_finished/<int:pk>/',
         views.update_is_finished, name='update_is_finished'),
    path('getcalculation/', views.getcalculation, name='getcalculation'),
    path('getnessadata/', views.getnessadata, name='getnessadata'),
    path('getvasculardata/', views.getvasculardata, name='getvasculardata'),
    path('setnessadata/', views.setnessadata, name='setnessadata'),
    path('setvasculardata/', views.setvasculardata, name='setvasculardata'),
    path('getMedicines/', views.getMedicines, name='getMedicines'),
    path('deleteMedicine/<int:pk>/',
         views.deleteMedicine,
         name='deleteMedicine'),
    path('addMedicine/', views.addMedicine, name='addMedicine'),
    path('updatepics/', views.updatepics, name='updatepics'),
    path('addnessapics/', views.addnessapics, name='addnessapics'),
    path('getnessapics/', views.getnessapics, name='getnessapics'),
    path('addvascularpics/', views.addvascularpics, name='addvascularpics'),
    path('getvascularpics/', views.getvascularpics, name='getvascularpics'),
]
