# Generated by Django 4.2.4 on 2023-08-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='phoneNumber',
            field=models.CharField(default='+201111111111', max_length=255),
        ),
    ]
