# Generated by Django 4.2.4 on 2023-08-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='phoneNumber',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='PatientCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('assistant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.assistantprofile')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile')),
            ],
        ),
    ]
