# Generated by Django 4.2.4 on 2023-08-31 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_patientprofile_phonenumber_patientcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=255)),
                ('isSmoker', models.BooleanField()),
                ('isMaried', models.BooleanField()),
                ('type', models.CharField(choices=[('check', 'check'), ('recheck', 'recheck'), ('operation', 'operation')], max_length=255)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medicine', models.TextField(blank=True, null=True)),
                ('patientCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientcard')),
            ],
        ),
    ]
