# Generated by Django 4.2.4 on 2023-09-01 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_doctorcard_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
