# Generated by Django 4.2.4 on 2023-09-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_patientcard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantprofile',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorprofile'),
        ),
    ]
