# Generated by Django 4.2.4 on 2023-09-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_assistantprofile_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantprofile',
            name='clinicName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
