# Generated by Django 4.2.4 on 2023-09-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_assistantprofile_clinicname'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcard',
            name='Finished',
            field=models.BooleanField(default=False),
        ),
    ]
