# Generated by Django 4.2.4 on 2023-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_patientcard_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcard',
            name='date',
            field=models.DateField(default='2023-09-06'),
        ),
    ]
