# Generated by Django 4.2.4 on 2023-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_doctorcard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcard',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
