# Generated by Django 4.2.4 on 2023-09-06 20:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_doctorcard_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcard',
            name='analysis',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
        migrations.AddField(
            model_name='doctorcard',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
        migrations.AddField(
            model_name='doctorcard',
            name='xRays',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
    ]
