# Generated by Django 3.2.12 on 2023-09-08 13:22

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_doctorcard_analysis_doctorcard_prescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDoctorCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to2)),
                ('xRays', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to2)),
                ('prescription', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to2)),
                ('patientCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientcard')),
            ],
        ),
    ]
