# Generated by Django 3.2.12 on 2023-09-09 15:51

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_tempdoctorcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to)),
                ('xRays', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to)),
                ('prescription', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to)),
                ('doctorcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorcard')),
            ],
        ),
    ]
