# Generated by Django 3.2.12 on 2023-09-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20230910_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='NessaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childrennumber', models.IntegerField(blank=True, null=True)),
                ('childrensex', models.CharField(blank=True, max_length=255, null=True)),
                ('mariagedate', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('prevoperations', models.TextField(blank=True, null=True)),
                ('patientprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile')),
            ],
        ),
    ]
