# Generated by Django 3.2.12 on 2023-09-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_nessacard'),
    ]

    operations = [
        migrations.AddField(
            model_name='nessacard',
            name='doctorprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='nessacard',
            name='patientprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='nessacard',
            unique_together={('patientprofile', 'doctorprofile')},
        ),
    ]
