# Generated by Django 3.2.12 on 2023-09-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20230911_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nessacard',
            name='doctorprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='nessacard',
            name='patientprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile'),
        ),
    ]
