# Generated by Django 3.2.12 on 2023-09-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20230911_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorprofile')),
            ],
            options={
                'unique_together': {('doctor', 'name')},
            },
        ),
    ]
