# Generated by Django 3.2.12 on 2023-09-14 22:14

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_favoritemedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='NessaPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to3)),
                ('nessacard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.nessacard')),
            ],
        ),
    ]
