# Generated by Django 3.2.12 on 2023-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_nessapictures_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nessacard',
            name='childsex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('twin', 'twin')], default='male', max_length=255),
        ),
        migrations.AddField(
            model_name='nessacard',
            name='datebirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessacard',
            name='lastbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessacard',
            name='lastperiode',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nessacard',
            name='prevbirth',
            field=models.CharField(choices=[('normal', 'normal'), ('caesarean', 'caesarean')], default='normal', max_length=255),
        ),
        migrations.AddField(
            model_name='nessacard',
            name='typeofbirth',
            field=models.CharField(choices=[('normal', 'normal'), ('caesarean', 'caesarean')], default='normal', max_length=255),
        ),
    ]
