# Generated by Django 3.2.12 on 2023-09-17 20:46

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20230917_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='VascularCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HB', models.CharField(blank=True, max_length=255, null=True)),
                ('PLT', models.CharField(blank=True, max_length=255, null=True)),
                ('WBC', models.CharField(blank=True, max_length=255, null=True)),
                ('RBC', models.CharField(blank=True, max_length=255, null=True)),
                ('HTC', models.CharField(blank=True, max_length=255, null=True)),
                ('Cholesterol', models.CharField(blank=True, max_length=255, null=True)),
                ('TGC', models.CharField(blank=True, max_length=255, null=True)),
                ('LDL', models.CharField(blank=True, max_length=255, null=True)),
                ('HDL', models.CharField(blank=True, max_length=255, null=True)),
                ('VLDL', models.CharField(blank=True, max_length=255, null=True)),
                ('Urea', models.CharField(blank=True, max_length=255, null=True)),
                ('CREATE', models.CharField(blank=True, max_length=255, null=True)),
                ('SGOT', models.CharField(blank=True, max_length=255, null=True)),
                ('SGPT', models.CharField(blank=True, max_length=255, null=True)),
                ('PT', models.CharField(blank=True, max_length=255, null=True)),
                ('INR', models.CharField(blank=True, max_length=255, null=True)),
                ('HbA1c', models.CharField(blank=True, max_length=255, null=True)),
                ('Ddimer', models.CharField(blank=True, max_length=255, null=True)),
                ('FBS', models.CharField(blank=True, max_length=255, null=True)),
                ('PPBS', models.CharField(blank=True, max_length=255, null=True)),
                ('caTotal', models.CharField(blank=True, max_length=255, null=True)),
                ('caIoized', models.CharField(blank=True, max_length=255, null=True)),
                ('ESR', models.CharField(blank=True, max_length=255, null=True)),
                ('CRP', models.CharField(blank=True, max_length=255, null=True)),
                ('PTNC', models.CharField(blank=True, max_length=255, null=True)),
                ('PTNS', models.CharField(blank=True, max_length=255, null=True)),
                ('AntithrombinIII', models.CharField(blank=True, max_length=255, null=True)),
                ('Anticarviolipin', models.CharField(blank=True, max_length=255, null=True)),
                ('AntiLupus', models.CharField(blank=True, max_length=255, null=True)),
                ('Anticoagulant', models.CharField(blank=True, max_length=255, null=True)),
                ('ANA', models.CharField(blank=True, max_length=255, null=True)),
                ('ANCA', models.CharField(blank=True, max_length=255, null=True)),
                ('Factor', models.CharField(blank=True, max_length=255, null=True)),
                ('doctorprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorprofile')),
                ('patientprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile')),
            ],
            options={
                'unique_together': {('patientprofile', 'doctorprofile')},
            },
        ),
        migrations.CreateModel(
            name='VascularPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to4)),
                ('vascularcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vascularcard')),
            ],
        ),
    ]
