# Generated by Django 3.2.12 on 2023-09-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_vascularcard_vascularpictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nessacard',
            name='childsex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('twin', 'twin')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nessacard',
            name='prevbirth',
            field=models.CharField(blank=True, choices=[('normal', 'normal'), ('caesarean', 'caesarean')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nessacard',
            name='typeofbirth',
            field=models.CharField(blank=True, choices=[('normal', 'normal'), ('caesarean', 'caesarean')], max_length=255, null=True),
        ),
    ]
